### ISSUE TITLE
Bug modalbox when TextInput is focused

### ISSUE THREAD

**Issue by pewh** [maxs15/react-native-modalbox#102]
Steps to reproduce:
1. open modalbox
2. click TextInput (and keyboard shown)
3. close the modal (swipe or back button if `backButtonClose` is true)
4. open modalbox again, and **modalbox will just opened 0.1 second, then auto-close instantly**
5. if open modalbox again, it will show behavior normal (modalbox will open)

So, there's no problem on open-close modal, until keyboard is opened.

![a](https://cloud.githubusercontent.com/assets/881358/20641158/99e37830-b424-11e6-98c6-4920af50afcf.gif)

**Comment by pqkluan** [comment]
Same issues here, but mine won't open again untill the app reload.

**Comment by felipemartim** [comment]
@pewh I had the same problem.

I fixed it by calling Keyboard.dismiss() just before closing the modal.

**Comment by pqkluan** [comment]
@felipemartim That only work if the user clicks on a close button or something like that. I can't catch the background press and swipe up gesture event, so I have to disable them, pretty annoying.

**Comment by pewh** [comment]
Yes, me too

**Comment by gutosanches** [comment]
Same issue here too

**Comment by igorpan** [comment]
Hey guys, I stumbled upon the same issue. Upon some fiddling, I found out that unmounting and then mounting the modal again seems to be a workaround for this.

So I have made a wrapper component that encapsulates the dirty mounting hack.

```
import React, { Component } from 'react';
import Modal from 'react-native-modalbox';

export default class RoModal extends Component {
  constructor(props) {
    super(props);
    this.state = {
      number: 0
    };
  }

  _onClose = () => {
    this.setState({ number: this.state.number + 1 });
    if (this.props.onClose) {
      this.props.onClose();
    }
  };

  render() {
    return [this.state.number].map(() => (
      <Modal
        key={this.state.number}
        {...this.props}
        onClose={this._onClose}
      />
    ))[0];
  }
}
```

What it does is increment the `state.number` every time modal is closed. Since `state.number` is wired up to `key` property in the render array, Reacts thinks that it is another component and unmounts the old modal and mounts the new one.

It's dirty, but is completely encapsulated so once this is fixed it can just be removed.

**Comment by holyxiaoxin** [comment]
I'm facing the same problem here.

**Comment by deathslocus** [comment]
Can you try my PR fork (https://github.com/deathslocus/react-native-modalbox/tree/propcheck) and see if that fixes it?

**Comment by teyou** [comment]
@felipemartim it fixed my issue 👍
