### ISSUE TITLE
RN 0.13.0 aboveStatusBar prop no longer works

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-modalbox#14]
Modals show underneath the status bar.

**Comment by maxs15** [comment]
This is because now the version 1.2.0 is no longer based on [react-native-overlay](https://github.com/brentvatne/react-native-overlay).
We now use the the built-in Modal component that unfortunately doesn't offer this property..
Maybe you could open an issue on react-native? it would be a great feature to add !
At least it's still available in the 1.1.5 version

**Comment by MossP** [comment]
Ah, I see. Thanks for getting back to me. I'll adjust my layouts accordingly and raise an issue on React-Native. Thanks @maxs15 :)

I'm guessing this https://github.com/maxs15/react-native-modalbox/issues/13 might be due to the same thing?

**Comment by maxs15** [comment]
Great :+1: 
Could you please post the issue link when you're done so we can keep track of it.
Thanks

**Comment by MossP** [comment]
Create the issue here: https://github.com/facebook/react-native/issues/3446

**Comment by maxs15** [comment]
Finally I added back the react-native-overlay in the last version.. that way the development of the component won't be stuck.
The built-in Modal component is still too young, let's wait and see

**Comment by MossP** [comment]
Probably a good call hopefully the multiple modal feature will be addressed in RN given that the status bar feature has been dismissed already. Thanks again :) :+1:
