### ISSUE TITLE
the height is less than the correct display

### ISSUE THREAD

**Issue by cdmalcl** [maxs15/react-native-modalbox#67]
when
 backdrop={false} position={'bottom'}
the height is less than the correct display（about 20）

**Comment by dunhuang** [comment]
I have the same issue, which happens at the first time (not each time) when the modal's opening.
I think it is because the animate was started before the onLayout event was triggered so it is unable to get the correct height of container,  see http://facebook.github.io/react-native/docs/view.html#onlayout.  
For the time being, one dumb way is to add a timer to the function animateOpen()

  animateOpen() {
    this.stopAnimateClose();

    // Backdrop fadeIn
    if (this.props.backdrop)
      this.animateBackdropOpen();

    // Detecting modal position
    setTimeout(()=>{
      this.state.positionDest = this.calculateModalPosition(this.state.containerHeight, this.state.containerWidth);

      this.state.isAnimateOpen = true;
      this.state.animOpen = Animated.timing(
        this.state.position,
        {
          toValue: this.state.positionDest,
          duration: this.props.animationDuration,
          easing: Easing.elastic(0.8)
        }
      );
      this.state.animOpen.start(() => {
        this.state.isAnimateOpen = false;
        this.state.isOpen = true;
        if (this.props.onOpened) this.props.onOpened();
      });
    },0);

  }

**Comment by viix** [comment]
+ 1

**Comment by maxs15** [comment]
Sorry for the late reply, @dunhuang could you investigate the issue and submit a PR ?
Help would be much appreciated

**Comment by dunhuang** [comment]
@maxs15  I'll try when I'm less busy

**Comment by xiaobuu** [comment]
Hi @maxs15 ,  I've submit a PR which fix the issue #79

**Comment by maxs15** [comment]
Awesome @xiaobuu !
@dunhuang could you try if this fix the issue on your side ?

**Comment by dunhuang** [comment]
@maxs15  sorry for the late replay. I tried @xiaobuu 's code, it is working.

**Comment by maxs15** [comment]
PR merged 👍

**Comment by DavyDeDurpel** [comment]
I think this PR has a bad side effect.  If you update the state very fast between showing and not showing the modal, the modal remains open.  The problem seems to be that the timeout is not cancelled when the isOpen property is set to 'false' and the animation did not start yet.

I also think there's an opportunity to add an extra 'delay' property.  It would be a nice addition if we could customize the delay of the animation and a great selling point ;-)

**Comment by maxs15** [comment]
Damn didn't see that issue.. could you check for a potential fix and send a PR ? I'm not able to check it out right now.
What would be the purpose of a `delay` property ? There is already a `animationDuration` property if you're talking about the duration of the animation.

Thanks @DavyDeDurpel

**Comment by DavyDeDurpel** [comment]
The delay property postpones the animation until after a certain time has expired.  It's very useful in case you want for instance display a 'it will take some time' kind of message to the user.  You don't want to display it immediately but only after 1 or 2 seconds.  

I personally use this module to show a modal loading indicator. A delay property is very useful in this case.  Each loading indicator has a negative impact on the user experience so having a delay avoids displaying a loading indicator between each step (as in my app most communication is done with a REST interface). 

I'm rather new to the React/Git stuff so it will take me some time to make a PR for you.  I will try to have one ready by the end of next week (monday is a public holiday and the rest of the week it's going to be very sunny in Belgium ;-)

**Comment by maxs15** [comment]
I understand what you're trying to do @DavyDeDurpel but I think it's pretty easy to perform on your side.
I'm just trying to not complicate too much the library.
